[tool.poetry]
name = "onnx-testing"
version = "0.1.0"
description = ""
authors = ["Martin Høy <martin@hoy.priv.no>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
transformers = "^4.27.3"
torch = "^2.0.0"
pillow = "^9.4.0"
optimum = {extras = ["exporters"], version = "^1.7.3"}
onnxruntime = "^1.14.1"


[tool.poetry.group.dev.dependencies]
requests = "^2.28.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
